# pyproject.toml
[tool.black]
line-length = 120
target-version = ["py311"]

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
exclude = [
    "tests/",
    "evaluation/"
]

plugins = []
