# pyproject.toml
[tool.black]
line-length = 88
target-version = ["py310"]

[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true
exclude = [
    "tests/",
    "evaluation/"
]

plugins = []
